### ISSUE TITLE
add memory reordering

### ISSUE THREAD

**Issue by psteinb** [sqeazy/sqeazy#11]
add memory reordering in rasterized vs z-curve fashion. we aim for 2 levels of reordering: pixel wise and tile wise, the general matrix that this produces is:
```
|             | voxel raster | voxel Zcurve |
|-------------+--------------+--------------|
| tile raster | X            |              |
| tile Zcurve | X            |              |
```
Algorithms marked by `X` are currently being considered
@royerloic please comment and refine if needed

**Comment by psteinb** [comment]
tile and voxel rasterlike memory reordering has landed:
here are some benchmarks:

```
BM_vector_reorder<std::uint16_t>/256/8         458 ns        460 ns    1483702   530.749MB/s
BM_vector_reorder<std::uint16_t>/4k/8         1442 ns       1447 ns     487175   2.63648GB/s
BM_vector_reorder<std::uint16_t>/48k/8       10127 ns      10129 ns      64204   4.51931GB/s
BM_vector_reorder<std::uint16_t>/320k/8      97013 ns      97005 ns       7135   3.14598GB/s
BM_vector_reorder<std::uint16_t>/16M/8     9666942 ns    9666452 ns         72   1.61642GB/s
BM_vector_reorder<std::uint16_t>/32M/8    19604182 ns   19602471 ns         36   1.59419GB/s
```

versus plain scalar memory copies:

```
BM_vector_copy<std::uint16_t>/256         162 ns        164 ns    4267464   1.45532GB/s
BM_vector_copy<std::uint16_t>/4k          333 ns        335 ns    2100796   11.4036GB/s
BM_vector_copy<std::uint16_t>/48k        4735 ns       4733 ns     147762   9.67137GB/s
BM_vector_copy<std::uint16_t>/320k      43390 ns      43383 ns      16280   7.03451GB/s
BM_vector_copy<std::uint16_t>/16M     5996608 ns    5995850 ns        120   2.60597GB/s
BM_vector_copy<std::uint16_t>/32M    12263973 ns   12263471 ns         59   2.54822GB/s
```

Bottom line, if we are streaming from RAM, the reordering goes up to 60% of the available single-core memory bandwidth. if we are potentially in L2 this goes down to 45%.

**Comment by royerloic** [comment]
That's great Peter, one question, what are the tile dimensions?

**Comment by psteinb** [comment]
sorry, I wasn't really clear what these results mean:
`BM_vector_reorder<std::uint16_t>/32M/8`
- `BM_vector_reorder` benchmark name
- `std::uint16_t` benchmark type used (16bit unsigned integer in this case)
- `32M` number of elements in the array/stack (here 32*2^20)
- `8` tile size extension (I am using even tiles current, so this means a tile is 8x8x8)

**Comment by psteinb** [comment]
interesting enough the SIMD version is faster only by a margin (tile_size = 8):

```
BM_vector_reorder_simd<std::uint16_t>/4k         1293 ns       1297 ns     545724   2.94087GB/s
BM_vector_reorder_simd<std::uint16_t>/48k       13848 ns      13858 ns      50665   3.30322GB/s
BM_vector_reorder_simd<std::uint16_t>/320k      76244 ns      76253 ns       8953   4.00213GB/s
BM_vector_reorder_simd<std::uint16_t>/16M     7318374 ns    7318223 ns         97   2.13508GB/s
BM_vector_reorder_simd<std::uint16_t>/32M    18506343 ns   18506202 ns         37   1.68862GB/s
```

might be better with AVX2 broadcasts perhaps. But we are not there yet. it's called now in case the shape of the incoming stack complies with SIMD block sizes.

**Comment by psteinb** [comment]
rasterized memory reordering for now passes all tests, currently only pixel based raster memory reordering is implemented

**Comment by psteinb** [comment]
just ran some tests, 

```
./sqy compress -p "bitswap1->lz4" -o wo_reordering.sqy Keller_TM0066_Droso_HisGFP.tif
./sqy compress -p "memory_reorder->bitswap1->lz4" -o reordered.sqy Keller_TM0066_Droso_HisGFP.tif
```

timings are comparable and overall bandwidth is not decreased due to memory reordering. the produced compressed file is 2 MB smaller than the one without memory reordering (total file size 62MB). So that a big win, but a gain.

**Comment by psteinb** [comment]
I've just pushed zcurve based memory reordering, it tends to be slow on arbitrary data due to quite some difficulties handling the borders, I'll close this thread now
