### ISSUE TITLE
remove_background and rmbkrd_neighbor5x5x5 not working for decompression

### ISSUE THREAD

**Issue by maweigert** [sqeazy/sqeazy#2]
As of now (35789b2d3213) the following sinks are not working:

a) remove_background
b) rmbkrd_neighbor5x5x5
c) rmestbkrd

a) and b) compress fine but throw an error at decompression while
c) errors out already at compression

**Comment by psteinb** [comment]
I suggest to split this into 2 issues first. let's keep this issue active for a+b and defer c to #3. What was the input image used?

**Comment by maweigert** [comment]
roundtrips for remove_background only didn't work on 8bit input data (e.g. flybrain.tif), whereas rmbkrd_neighbor5x5x5 didn't work on any image

**Comment by psteinb** [comment]
the decompression error for remove_background boils down to the pipeline string not being parsed correctly upon decompression, I'm on it

**Comment by psteinb** [comment]
this error is gone for me, please check and close this issue if you can confirm

**Comment by maweigert** [comment]
Works on OSX 10.10.
