### ISSUE TITLE
rmestbkrd not working

### ISSUE THREAD

**Issue by psteinb** [sqeazy/sqeazy#3]
as reported in #2, @maweigert observed that rmestbkrd errors out already at compression in https://github.com/sqeazy/sqeazy/commit/35789b2d3213d3bdd6ae9d42ef7087623306f127

**Comment by maweigert** [comment]
error message:
$sqy comp -p rmestbkrd  Volvis_arteries256.tif -o foo.sqy

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: sqeazy/src/cpp/src/./dynamic_stage.hpp:418 encode wrote past the end of temporary buffers

**Comment by psteinb** [comment]
interesting, I am able to reproduce it under Linux. I am having a look.

**Comment by psteinb** [comment]
please check on your side and close this ticket if you find that the bug is fixed

**Comment by maweigert** [comment]
Can confirm that it works now on OSX 10.10.
Can be closed (I don't seem to have permission to)
