### ISSUE TITLE
SSE enabled bitswapping not faster than normal bitswapping on OSX

### ISSUE THREAD

**Issue by psteinb** [sqeazy/sqeazy#5]
@maweigert reported that experimental implementation of bitswapping is not faster than normal version under OSX. 

Checking under Linux, I see that the SSE method is not used when SQY_EXPERIMENTAL is switched on.

**Comment by psteinb** [comment]
I fixed one bug, that showed me that the SSE implementation yields some bugs when confronted with 8-bit input, 16-bit input works

**Comment by psteinb** [comment]
I had a look at the code and saw that I would need to invest too much time to make it work for 8-bit for now. I put it on the TODO list as it is an experimental feature anyhow, but it should be in as 8-bit data is common.
@maweigert Please check the runtimes for 16-bit input data on OSX! If they are about 2x apart as on my machine (SSE is about 2x faster than the standard version), I suggest to close this issue.

**Comment by maweigert** [comment]
Can confirm that SSE works on OSX 10.10 and yields the expected speed up. Cool!  (can be closed)

**Comment by psteinb** [comment]
I'll close this then
