### ISSUE TITLE
logo for sqeazy

### ISSUE THREAD

**Issue by worlwide** [sqeazy/sqeazy#73]
Hello there. I design a logo in my free time. I want to design a logo for you. What do you think ? I want to contribute you.

**Comment by psteinb** [comment]
but we already have a [logo](https://github.com/sqeazy) ?!

**Comment by worlwide** [comment]
oh sorry :)

**Comment by psteinb** [comment]
No need to be sorry. I appreciate your courage to approach us and offer 
your help. Keep going!

**Comment by psteinb** [comment]
I'll close this issue. if more room for discussion is needed, feel free to reopen.
